version: '3.8'

services:
  backend:
    image: oven/bun:latest
    working_dir: /app
    command: ["bun", "index.ts"]
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    image: node:18
    working_dir: /app
    command: /bin/bash -c "npm install && npm start"
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development